name: PDF creator

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: create file list
        id: files_list
        run: |
          echo "usepackage{tcolorbox}" > quote.tex
          echo "newtcolorbox{myquote}{colback=red!5!white, colframe=red!75!black}" >> quote.tex
          echo "renewenvironment{quote}{\begin{myquote}}{\end{myquote}}" >> quote.tex
          cat quote.tex
          mkdir output  
          echo "files=$(printf '"%s" ' *.md)" > $GITHUB_OUTPUT
#      - uses: docker://rstropek/pandoc-latex
      - uses: docker://rstropek/pandoc-latex
        with:
#          args: --pdf-engine=xelatex -f markdown --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v2.0.0/eisvogel.tex -t latex --output=output/result.pdf ${{ steps.files_list.outputs.files }}
          args: --pdf-engine=xelatex -f gfm --toc --include-in-header titlesec.tex -V linkcolor:blue -t latex --output=output/result.pdf ${{ steps.files_list.outputs.files }}
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output

#    - name: Commit files
#      run: |
#        git config --local user.email ${{ secrets.GIT_EMAIL }}
#        git config --local user.name ${{ secrets.GIT_NAME }}
#        git commit -am "Upload PDFs"
#
#    - name: Push changes
#      uses: ad-m/github-push-action@master
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        branch: main
#      env:
#        CI: true